---
plugin: aws_ec2
aws_access_key: 
aws_secret_key: 
regions:
  - us-east-1
keyed_groups:
  - key: tags.K3s
    prefix: K3s
filters:
  instance-state-name: running
hostnames:
  - tag:Name
  - instance-id
  - public_ip_address
compose:
  ansible_host: public_ip_address
